
name : Test


on :
    workflow_dispatch :
    pull_request :
        branches : [ Stable ]


jobs :
    publish :

        runs-on : ubuntu-latest

        strategy :
            matrix :
                deno-version : [ v1.41.x ]

        steps :

            -   name : Checkout Repository
                uses : actions/checkout@v4

            -   name : Setup Deno
                uses : denoland/setup-deno@v1
                with :
                    deno-version : ${{ matrix.deno-version }}

            -   name : Run Tests
                run : deno test
